/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Screen;

import Entities.HocSinh;
import JDBC.DBHocPhan;
import JDBC.DBHocSinh;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fr13nd
 */
public class FrDanhSachHocSinh extends javax.swing.JFrame {
    private DefaultTableModel tableModel;
    private ArrayList<HocSinh> dsHS, dsLop;
    private String maHP;
    private String[] dsMaHS;
    private int soLuong;
    
    /**
     * Creates new form FrDanhSachHocSinh
     */
    public FrDanhSachHocSinh(String maHP, ArrayList<HocSinh> dsLop) {
        dsHS = new ArrayList<HocSinh>();
        this.dsMaHS = new String[100];
        this.maHP = maHP;
        this.soLuong =0;
        this.dsLop = dsLop;
        System.out.println("DANH SACH LOP DUOC TRUYEN VAO: "+ dsLop.size());
        //setUndecorated(true);
        initComponents();
        setLocation(100,100);
        
        //khoi tao noi duung cho Frame
        initContent();
    }
    public FrDanhSachHocSinh() {
        dsHS = new ArrayList<HocSinh>();
        this.maHP = null;
        btnThemHocSinhVaoDanhSachLop.setVisible(false);
        
        initComponents();
        setLocation(100,100);
        //setUndecorated(true);
        btnThemHocSinhVaoDanhSachLop.setVisible(false);
        //khoi tao noi duung cho Frame
        initContent();
    }
    
    private void initContent(){
        //khong cho cac nut hien thi
        btnXacNhan.setVisible(false);
        btnHuy.setVisible(false);
        //set mau cho cua so
        this.setBackground(new Color(0,255,153));
        
        System.out.println("- Chuan bi lay du lieu cua hoc sinh: ");
        tableModel = (DefaultTableModel) tbDSLop.getModel();
        tableModel.setRowCount(0);
        Vector row;
        
        //lay du lieu tu database
        DBHocSinh dbHS = new DBHocSinh();
        dsHS = dbHS.layDSHS();
        HocSinh  hs, soSanhHS;
        for(int i=0 ; i<dsHS.size(); i++){
            hs = dsHS.get(i);
            row = new Vector();
            row.add(hs.getUsername());
            row.add(hs.getHoTen());
            row.add(hs.getNgaySinh().toString());
            row.add(hs.getCmnd());
            row.add(hs.getDiaChi());
            row.add(hs.getKhoiLop());
            row.add(hs.getTenTruong());
            //them hang cho bang
            tableModel.addRow(row);
        }
        
        //tbDSLop.setModel(tableModel);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbDSLop = new javax.swing.JTable();
        btnThemHocSinhVaoDanhSachLop = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lbChonMaSV = new javax.swing.JLabel();
        btnXacNhan = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        lbSoHSDaChon = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 255, 153));

        tbDSLop.setBackground(new java.awt.Color(204, 204, 255));
        tbDSLop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Họ tên", "Ngày sinh", "CMND", "Quê quán", "Lớp", "Tên trường"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbDSLop);

        btnThemHocSinhVaoDanhSachLop.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnThemHocSinhVaoDanhSachLop.setText("Thêm học sinh vào danh sách lớp");
        btnThemHocSinhVaoDanhSachLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemHocSinhVaoDanhSachLopActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Thoát");
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbChonMaSV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbChonMaSV.setForeground(new java.awt.Color(0, 0, 204));
        lbChonMaSV.setText("Số sinh viên đã chọn:");

        btnXacNhan.setBackground(new java.awt.Color(0, 255, 204));
        btnXacNhan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnXacNhan.setText("Xác nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        btnHuy.setBackground(new java.awt.Color(204, 204, 255));
        btnHuy.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        lbSoHSDaChon.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbSoHSDaChon.setForeground(new java.awt.Color(0, 0, 204));
        lbSoHSDaChon.setText("      ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbSoHSDaChon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThemHocSinhVaoDanhSachLop, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXacNhan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHuy))
                    .addComponent(lbChonMaSV))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemHocSinhVaoDanhSachLop)
                    .addComponent(btnXacNhan)
                    .addComponent(btnHuy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbChonMaSV)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lbSoHSDaChon))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemHocSinhVaoDanhSachLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemHocSinhVaoDanhSachLopActionPerformed

        //lay danh sach nhung hoc sinh da chon
        int[] dsChon = new int[100];
        dsChon = tbDSLop.getSelectedRows();
        soLuong = tbDSLop.getSelectedRowCount();
        //lay mang nhung ma sinh vien de them vao         
        for(int i=0; i<soLuong; i++){
            dsMaHS[i] = dsHS.get(dsChon[i]).getUsername();
        }
        lbSoHSDaChon.setText(soLuong+"");
        //kiem tra so luong hoc sinh da duoc chon
        for(int j =0; j< soLuong; j++){
            System.out.println("\tHoc sinh da chon thu "+j+" la: "+ dsMaHS[j]);
        }
        
        if(tbDSLop.getSelectedRow() >= 0){
            btnXacNhan.setVisible(true);
            btnHuy.setVisible(true);
        }
       
    }//GEN-LAST:event_btnThemHocSinhVaoDanhSachLopActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        // TODO add your handling code here:
        //kiem tra hoc sinh da co san trong lop thi khong them
        DBHocPhan dbHP = new DBHocPhan();
        String ktMahs, mahs1, mahs2;
        int trungHS;
        for(int i = 0; i<soLuong; i++){
            ktMahs = dsMaHS[i];
            trungHS =0;
            //kiem tra hoc sinh da co trong danh sach lop chua
            for(int j = 0; j<dsLop.size(); j++){
                if(ktMahs.trim().equals(dsLop.get(j).getUsername().trim())){
                    trungHS ++;
                }  
            }
            //xem xet hoc sinh co trung khong, khong trung thi them vao
            if(trungHS == 0){
                System.out.println("\t- Them hoc sinh vao hoc phan");
                dbHP.themHSvaoHP(ktMahs, maHP);
            }else{
                System.out.println("\t** Da ton tai hoc sinh "+ ktMahs);
            }
        }
        this.setVisible(false);
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnHuyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnThemHocSinhVaoDanhSachLop;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbChonMaSV;
    private javax.swing.JLabel lbSoHSDaChon;
    private javax.swing.JTable tbDSLop;
    // End of variables declaration//GEN-END:variables
}
