/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Screen;

import Entities.HocSinh;
import JDBC.DBHocSinh;
import JDBC.DangNhap;
import java.text.ParseException;
import java.text.SimpleDateFormat;
//import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Fr13nd
 */
public class FrSuaHocSinh extends javax.swing.JFrame {
    
    private String maHP;
    private HocSinh hs;
    
    /**
     * Creates new form FrThemHocSinh
     */
    public FrSuaHocSinh(HocSinh hs) {
        this.maHP = maHP;
        this.hs = hs;
        
        initComponents();
        this.setLocation(200, 100);
        // phai dung sau component vi initcomponent se tao cac textbox cho initcontent do du lieu vao   
        initContent();
        
    }
    
    private void initContent(){
        System.out.println("\n\t"+ hs.getUsername());
        txt1idHS.setText(hs.getUsername());
        txt1idHS.setEditable(false);
        txt2hoTen.setText(hs.getHoTen());
        txt3ngaySinh.setText("YYYYMMDD");
        txt4soCMND.setText(hs.getCmnd());
        txt5diaChi.setText(hs.getDiaChi());
        txt6khoiLop.setText(hs.getKhoiLop()+"");
        txt7tenTruong.setText(hs.getTenTruong());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt1idHS = new javax.swing.JTextField();
        txt2hoTen = new javax.swing.JTextField();
        txt3ngaySinh = new javax.swing.JTextField();
        txt4soCMND = new javax.swing.JTextField();
        txt5diaChi = new javax.swing.JTextField();
        txt6khoiLop = new javax.swing.JTextField();
        txt7tenTruong = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnLuu = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();

        setTitle("Thêm học sinh mới");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("ID học sinh:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Họ tên:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Ngày sinh:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Số CMND:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Địa chỉ:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Học sinh khối:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Tên trường:");

        txt1idHS.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txt2hoTen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txt3ngaySinh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt3ngaySinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt3ngaySinhActionPerformed(evt);
            }
        });

        txt4soCMND.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txt5diaChi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txt6khoiLop.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txt7tenTruong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel8.setText("định dạng: YYYYMMDD ");

        btnLuu.setBackground(new java.awt.Color(51, 255, 255));
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnHuy.setBackground(new java.awt.Color(255, 0, 0));
        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt6khoiLop, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt5diaChi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt4soCMND, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt3ngaySinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt2hoTen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt1idHS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(btnHuy))
                            .addComponent(txt7tenTruong, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt1idHS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt2hoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt3ngaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt4soCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt5diaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt6khoiLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt7tenTruong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLuu)
                    .addComponent(btnHuy))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt3ngaySinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt3ngaySinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt3ngaySinhActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        if(txt1idHS.getText() != null
            && txt2hoTen.getText() != null
            && txt3ngaySinh.getText() != null
            && txt4soCMND.getText()!= null
            && txt5diaChi.getText() != null
            && txt6khoiLop.getText() != null
            && txt7tenTruong.getText() != null)
        {
            try {
                capNhatHocSinh();
                JOptionPane.showMessageDialog(this, "Sửa thành công", "Sửa thông tin", JOptionPane.INFORMATION_MESSAGE);
            } catch (ParseException ex) {
                Logger.getLogger(FrSuaHocSinh.class.getName()).log(Level.SEVERE, null, ex);
                //hien thi thong bao nhap sai dinh dang ngay
            }
        }else {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập đầy đủ thông tin", "Nhập thông tin", JOptionPane.INFORMATION_MESSAGE);
        }
     this.setVisible(false);
    }//GEN-LAST:event_btnLuuActionPerformed

    private void capNhatHocSinh() throws ParseException{
        
        String id = txt1idHS.getText();
        String hoTen = txt2hoTen.getText();
        String ngaySinh = txt3ngaySinh.getText();
        String soCMND = txt4soCMND.getText();
        String diaChi = txt5diaChi.getText();
        int lop = Integer.parseInt(txt6khoiLop.getText());
        String tenTruong = txt7tenTruong.getText();
        
        HocSinh hs = new HocSinh();
        hs.setUsername(id);
        hs.setHoTen(hoTen);
        hs.setDiaChi(diaChi);
        hs.setCmnd(soCMND);
        hs.setKhoiLop(lop);
        
        //them ngay sinh
        hs.setNgaySinh(dinhDangNgay(ngaySinh));
        hs.setTenTruong(tenTruong);
        
        DBHocSinh dbHS = new DBHocSinh();
        dbHS.suaHS(hs);
//        DangNhap dbDangNhap = new DangNhap();
//        dbDangNhap.themDangNhap(hs.getUsername(), "123", "HS");
        
        
    }
    
    private Date dinhDangNgay(String dinhDang){
        System.out.println("Dinh dang: YYYYMMDD");
        String nam = dinhDang.substring(0, 4); System.out.println("\tnam nhan duoc:"+ nam);
        String thang = dinhDang.substring(4, 6); System.out.println("\tthang nhan duoc:"+ thang);
        String ngay = dinhDang.substring(6); System.out.println("\tngay nhan duoc:"+ ngay);
        
        int ngayInt, thangInt, namInt;
        ngayInt = Integer.parseInt(ngay);
        thangInt = Integer.parseInt(thang) -1;
        namInt = Integer.parseInt(nam) - 1900;
        Date date = new Date(namInt, thangInt, ngayInt);
        return date;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txt1idHS;
    private javax.swing.JTextField txt2hoTen;
    private javax.swing.JTextField txt3ngaySinh;
    private javax.swing.JTextField txt4soCMND;
    private javax.swing.JTextField txt5diaChi;
    private javax.swing.JTextField txt6khoiLop;
    private javax.swing.JTextField txt7tenTruong;
    // End of variables declaration//GEN-END:variables
}
