/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Screen;

import Entities.BangDiem;
import Entities.HocSinh;
import JDBC.DBHocPhan;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.Hashtable;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fr13nd
 */
public class FrXemBangDiem extends javax.swing.JFrame implements ListSelectionListener{
    private String maHP;
    private Hashtable<String,String> dataHocPhan;
    private ArrayList<HocSinh> dsLop;
    private DefaultTableModel tableModel;
    private  ArrayList<BangDiem> dsBangDiem;
    private DBHocPhan dbHocPhan;
    private int viTri;
    
    @Override
    public void print(Graphics g) {
        super.print(g); //To change body of generated methods, choose Tools | Templates.
    }
    
    /**
     * Creates new form XemBangDiem
     */
    public FrXemBangDiem(Hashtable<String,String> dataHocPhan,String maHP, ArrayList<HocSinh> dsLop) {
        this.maHP = maHP;
        this.dataHocPhan = dataHocPhan;
        this.dsLop = dsLop;
        this.tableModel = null;
        this.dsBangDiem = null;
        this.dbHocPhan = new DBHocPhan();
        this.viTri =0;
        
        initComponents();
        initContent();
    }
    
    private void initContent(){
        
        doDuLieu();
        
        pnSuaLbCC.setVisible(false);
        pnSuaLbCK.setVisible(false);
        pnSuaLbGK.setVisible(false);
        pnSuaLbHienThiTen.setVisible(false);
        pnSuaLbTen.setVisible(false);
        pnSuatxtCC.setVisible(false);
        pnSuatxtCK.setVisible(false);
        pnSuatxtGK.setVisible(false);
        pnSuaBtnNext.setVisible(false);
        pnSuaBtnPrev.setVisible(false);
    }
    
    private void doDuLieu(){
        System.out.println("\t- Lay và do du lieu");
        //lay ten hoc phan trong data hocphan
        String tenHP;
        for(String key : dataHocPhan.keySet()){
            if(dataHocPhan.get(key).equals(maHP))
                tenHP = dataHocPhan.get(key);
        }
        //lay bang diem theo ma sv
        DBHocPhan dbHP = new DBHocPhan();
        dsBangDiem = dbHP.layBangDiem(dsLop);
               
        //do du lieu ra view
        tableModel = (DefaultTableModel) tbBangDiem.getModel();
        tableModel.setRowCount(0);
        Vector row;
        
        System.out.println("\t* DS Bang diem: "+ dsBangDiem.size()+
                " - DS Hoc Sinh: "+dsLop.size());
        for(int i = 0; i< dsBangDiem.size(); i++){
            row = new Vector();
            row.add(dsBangDiem.get(i).getidHS());
            row.add(dsLop.get(i).getHoTen());
            row.add(dsBangDiem.get(i).getChuyenCan());
            row.add(dsBangDiem.get(i).getGiuaKy());
            row.add(dsBangDiem.get(i).getCuoiKy());
            tableModel.addRow(row);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbBangDiem = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnXuaDiem = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        pnSuaLbTen = new javax.swing.JLabel();
        pnSuaLbHienThiTen = new javax.swing.JLabel();
        pnSuaLbCC = new javax.swing.JLabel();
        pnSuatxtCC = new javax.swing.JTextField();
        pnSuaLbGK = new javax.swing.JLabel();
        pnSuatxtGK = new javax.swing.JTextField();
        pnSuatxtCK = new javax.swing.JTextField();
        pnSuaLbCK = new javax.swing.JLabel();
        pnSuaBtnPrev = new javax.swing.JButton();
        pnSuaBtnNext = new javax.swing.JButton();

        tbBangDiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Học Sinh", "Họ và Tên", "Chuyên cần", "Giữa kỳ", "Cuối Kỳ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbBangDiem);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("BẢNG ĐIỂM");

        btnXuaDiem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnXuaDiem.setText("Xửa điểm");
        btnXuaDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuaDiemActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Vui lòng chọn học sinh");

        pnSuaLbTen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pnSuaLbTen.setText("Họ tên:");

        pnSuaLbHienThiTen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pnSuaLbHienThiTen.setForeground(new java.awt.Color(0, 0, 204));
        pnSuaLbHienThiTen.setText("         ");

        pnSuaLbCC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pnSuaLbCC.setText("CC:");

        pnSuatxtCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnSuatxtCCActionPerformed(evt);
            }
        });

        pnSuaLbGK.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pnSuaLbGK.setText("GK:");

        pnSuaLbCK.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pnSuaLbCK.setText("CK:");

        pnSuaBtnPrev.setText("<<");
        pnSuaBtnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnSuaBtnPrevActionPerformed(evt);
            }
        });

        pnSuaBtnNext.setText(">>");
        pnSuaBtnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnSuaBtnNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(btnXuaDiem))
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(pnSuaLbTen)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pnSuaLbHienThiTen, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(pnSuaBtnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(pnSuaLbCC, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(pnSuatxtCC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(pnSuaLbGK, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(pnSuatxtGK, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(pnSuaLbCK, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(pnSuatxtCK, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(36, 36, 36)
                                                .addComponent(pnSuaBtnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pnSuaLbTen)
                    .addComponent(pnSuaLbHienThiTen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pnSuaLbCK)
                        .addComponent(pnSuatxtCK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnXuaDiem)
                        .addComponent(pnSuaLbCC)
                        .addComponent(pnSuatxtCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pnSuaLbGK)
                        .addComponent(pnSuatxtGK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pnSuaBtnPrev)
                    .addComponent(pnSuaBtnNext))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXuaDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuaDiemActionPerformed
        // TODO add your handling code here:
        pnSuaLbCC.setVisible(true);
        pnSuaLbCK.setVisible(true);
        pnSuaLbGK.setVisible(true);
        pnSuaLbHienThiTen.setVisible(true);
        pnSuaLbTen.setVisible(true);
        pnSuatxtCC.setVisible(true);
        pnSuatxtCK.setVisible(true);
        pnSuatxtGK.setVisible(true);
        pnSuaBtnNext.setVisible(true);
        pnSuaBtnPrev.setVisible(false);
        
        //do du lieu de sua
        pnSuaLbHienThiTen.setText(dsLop.get(viTri).getHoTen());
        pnSuatxtCC.setText(dsBangDiem.get(viTri).getChuyenCan()+"");
        pnSuatxtGK.setText(dsBangDiem.get(viTri).getGiuaKy()+"");
        pnSuatxtCK.setText(dsBangDiem.get(viTri).getCuoiKy()+"");
    }//GEN-LAST:event_btnXuaDiemActionPerformed

    private void suaDiem(int viTri){
        
    }
    
    private void pnSuatxtCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnSuatxtCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnSuatxtCCActionPerformed

    private void pnSuaBtnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnSuaBtnNextActionPerformed
        // TODO add your handling code here:
        pnSuaBtnPrev.setVisible(true);
        
        //lay du lieu de sua 
        int cc= 5, gk= 5;
        float ck =5;
        try {
            cc = Integer.parseInt(pnSuatxtCC.getText());
            gk = Integer.parseInt(pnSuatxtGK.getText());
            ck = Float.parseFloat(pnSuatxtCK.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Lỗi nhập liệu!");
        }
        dbHocPhan.capNhatDiem(dsLop.get(viTri).getUsername(), cc, gk, ck);
        if(viTri < dsLop.size() -1)
            viTri ++;
        
        //cap nhat du lieu cho phan sau
        pnSuaLbHienThiTen.setText(dsLop.get(viTri).getHoTen());
        pnSuatxtCC.setText(dsBangDiem.get(viTri).getChuyenCan()+"");
        pnSuatxtGK.setText(dsBangDiem.get(viTri).getGiuaKy()+"");
        pnSuatxtCK.setText(dsBangDiem.get(viTri).getCuoiKy()+"");
        
        doDuLieu();
    }//GEN-LAST:event_pnSuaBtnNextActionPerformed

    private void pnSuaBtnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnSuaBtnPrevActionPerformed
        // TODO add your handling code here:
        //lay du lieu de sua 
        int cc= 5, gk= 5;
        float ck =5;
        try {
            cc = Integer.parseInt(pnSuatxtCC.getText());
            gk = Integer.parseInt(pnSuatxtGK.getText());
            ck = Float.parseFloat(pnSuatxtCK.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Lỗi nhập liệu!");
        }
        dbHocPhan.capNhatDiem(dsLop.get(viTri).getUsername(), cc, gk, ck);
        
        if(viTri>0)
            viTri --;
        
        //cap nhat du lieu cho phan sau
        pnSuaLbHienThiTen.setText(dsLop.get(viTri).getHoTen());
        pnSuatxtCC.setText(dsBangDiem.get(viTri).getChuyenCan()+"");
        pnSuatxtGK.setText(dsBangDiem.get(viTri).getGiuaKy()+"");
        pnSuatxtCK.setText(dsBangDiem.get(viTri).getCuoiKy()+"");
        
        doDuLieu();
    }//GEN-LAST:event_pnSuaBtnPrevActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXuaDiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pnSuaBtnNext;
    private javax.swing.JButton pnSuaBtnPrev;
    private javax.swing.JLabel pnSuaLbCC;
    private javax.swing.JLabel pnSuaLbCK;
    private javax.swing.JLabel pnSuaLbGK;
    private javax.swing.JLabel pnSuaLbHienThiTen;
    private javax.swing.JLabel pnSuaLbTen;
    private javax.swing.JTextField pnSuatxtCC;
    private javax.swing.JTextField pnSuatxtCK;
    private javax.swing.JTextField pnSuatxtGK;
    private javax.swing.JTable tbBangDiem;
    // End of variables declaration//GEN-END:variables

    @Override
    public void valueChanged(ListSelectionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
